### ISSUE TITLE
Buyer Use Case diagram

### ISSUE THREAD

**Issue by Kmm1316** [Kmm1316/Group7E-Commerce#16]
Review use cases for the Buyer/Customer Class and create a use case diagram for this class, The Use case you choose is your decision

**Comment by CharliesPants** [comment]
Creating diagram for the Login Use case.

**Comment by CharliesPants** [comment]
![Image](https://github.com/user-attachments/assets/8e0cd986-43e5-42b1-940a-d367b02340b5)


Updated buyer use case diagram
