### ISSUE TITLE
Admin Use Case diagram

### ISSUE THREAD

**Issue by Kmm1316** [Kmm1316/Group7E-Commerce#18]
Review Use cases for Admin class, Create relative diagram, Use case is your decision

**Comment by Kmm1316** [comment]
![AdminUseCase drawio](https://github.com/user-attachments/assets/6ee3d0a0-afe1-4481-9e83-bd2163d8a49a)
This is my diagram if anyone thinks I need to include anything else please let me know

**Comment by Kmm1316** [comment]
![AdminUseCaseDiagram](https://github.com/user-attachments/assets/f29b0e03-96fa-4031-b73a-699e59eb2296)
This is my diagram, please let me know if it needs to be changed

**Comment by aayamrajshakya** [comment]
I might be wrong, but does the admin have the privilege to add items to the inventory as well? I thought admins could only remove items that they find inappropriate.
